name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Review Test
        run: mvn -Dtest=ReviewTests test
      - name: User Test
        run: mvn -Dtest=UserTests test
      - name: Restaurant Test
        run: mvn -Dtest=RestaurantTests test
      - name: Revenue Test
        run: mvn -Dtest=RevenueTests test
      - name: Dish Test
        run: mvn -Dtest=DishTests test
      - name: Bookmark Test
        run: mvn -Dtest=BookmarkTests test
      - name: OrderDish Test
        run: mvn -Dtest=OrderDishTests test
      - name: OrderProfile Test
        run: mvn -Dtest=OrderProfileTests test
      - name: Generate test reports
        run: mvn surefire-report:report  
        
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cs4156_drinkmorewater

