name: Java CI

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Review Test
        run: mvn -Dtest=ReviewTests test
      - name: User Test
        run: mvn -Dtest=UserTests test
      - name: Restaurant Test
        run: mvn -Dtest=RestaurantTests test
      - name: Revenue Test
        run: mvn -Dtest=RevenueTests test
      - name: Dish Test
        run: mvn -Dtest=DishTests test
      - name: Bookmark Test
        run: mvn -Dtest=BookmarkTests test
      - name: OrderDish Test
        run: mvn -Dtest=OrderDishTests test
      - name: OrderProfile Test
        run: mvn -Dtest=OrderProfileTests test
      - name: Generate test reports
        run: mvn surefire-report:report
      - name: Run Spotbugs
        run: mvn -B verify spotbugs:spotbugs
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
      - name: Export test results
        run: cp target/surefire-reports/*.txt CIResults
      - uses: EndBug/add-and-commit@v7
        with:
          add: CIResults/.
          default_actor: github_actions
